modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
[[mixins]]
config="${mod_id}.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="${mod_url}"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "cloth_config"
type="required"
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "modular_machinery_reborn"
type="required"
versionRange = "[${mmr_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ae2"
type="required"
versionRange = "[${ae2_version},)"
ordering = "AFTER"
side = "BOTH"